[build-system]
requires = ["setuptools>=30.3.0", "setuptools_scm", "wheel"]

[tool.black]
line-length = 120
force-exclude = "/(asdf/extern|.eggs|.tox)/"

[tool.isort]
profile = "black"
filter_files = true
line_length = 120
extend_skip_glob = ["asdf/extern/*", ".eggs/*", ".tox/*"]
