name: Downstream

on:
  workflow_dispatch:
    inputs:
      astropy_ref:
        description: astropy ref
        required: true
        default: main
      dkist_ref:
        description: dkist ref
        required: true
        default: main
      gwcs_ref:
        description: gwcs ref
        required: true
        default: master
      jwst_ref:
        description: jwst ref
        required: true
        default: master
      specutils_ref:
        description: specutils ref
        required: true
        default: main
      sunpy_ref:
        description: sunpy ref
        required: true
        default: main
      weldx_ref:
        description: weldx ref
        required: true
        default: master
      asdf-astropy_ref:
        description: asdf-astropy ref
        required: true
        default: main
      asdf-transform-schemas_ref:
        description: asdf-transform-schemas ref
        required: true
        default: master
      asdf-wcs-schemas_ref:
        description: asdf-wcs-schemas ref
        required: true
        default: main
      asdf-coordinates-schemas_ref:
        description: asdf-coordinates-schemas ref
        required: true
        default: main
  schedule:
    # Run every Monday at 6am UTC
    - cron: '0 6 * * 1'

env:
  CRDS_SERVER_URL: https://jwst-crds.stsci.edu
  CRDS_PATH: ~/crds_cache
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

jobs:
  common:
    name: ${{ matrix.package_name }}@${{ matrix.ref }} unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package_name: astropy
            repository: astropy/astropy
            ref: ${{ github.event.inputs.astropy_ref || 'main' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: gwcs
            repository: spacetelescope/gwcs
            ref: ${{ github.event.inputs.gwcs_ref || 'master' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: jwst
            repository: spacetelescope/jwst
            ref: ${{ github.event.inputs.jwst_ref || 'master' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: specutils
            repository: astropy/specutils
            ref: ${{ github.event.inputs.specutils_ref || 'main' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: weldx
            repository: BAMWelDX/weldx
            ref: ${{ github.event.inputs.weldx_ref || 'master' }}
            install_command: pip install -e .[test]
            test_command: pytest weldx/tests/asdf_tests weldx/schemas --asdf-tests
          - package_name: sunpy
            repository: sunpy/sunpy
            ref: ${{ github.event.inputs.sunpy_ref || 'main' }}
            install_command: pip install -e .[tests,all]
            test_command: pytest sunpy/io/
          - package_name: dkist
            repository: DKISTDC/dkist
            ref: ${{ github.event.inputs.dkist_ref || 'main' }}
            install_command: pip install -e .[tests]
            test_command: pytest
          - package_name: asdf-astropy
            repository: astropy/asdf-astropy
            ref: ${{ github.event.inputs.asdf-astropy_ref || 'main' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: asdf-transform-schemas
            repository: asdf-format/asdf-transform-schemas
            ref: ${{ github.event.inputs.asdf-transform-schemas_ref || 'master' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: asdf-wcs-schemas
            repository: asdf-format/asdf-wcs-schemas
            ref: ${{ github.event.inputs.asdf-wcs-schemas_ref || 'main' }}
            install_command: pip install -e .[test]
            test_command: pytest
          - package_name: asdf-coordinates-schemas
            repository: asdf-format/asdf-coordinates-schemas
            ref: ${{ github.event.inputs.asdf-coordinates-schemas_ref || 'main' }}
            install_command: pip install -e .[test]
            test_command: pytest
    steps:
      - name: Checkout asdf
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          path: asdf
      - name: Checkout ${{ matrix.package_name }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.ref }}
          path: target
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install asdf
        run: cd asdf && pip install .
      - name: Install remaining ${{ matrix.package_name }} dependencies
        run: cd target && ${{ matrix.install_command }}
      - name: Run ${{ matrix.package_name}} tests
        run: cd target && ${{ matrix.test_command }}
